### ISSUE TITLE
Easy Install?

### ISSUE THREAD

**Issue by sbromberger** [ilmari-h/dlv-tui#2]
Thank you for making this tool! I'm having a problem installing it:

```
seth@hydrogen:~ $ go install github.com/ilmari-h/dlv-tui@latest
go: github.com/ilmari-h/dlv-tui@latest: github.com/ilmari-h/dlv-tui@v0.0.0-20220628180326-dddbb0296c8e: parsing go.mod:
        module declares its path as: dlvtui
                but was required as: github.com/ilmari-h/dlv-tui
```

Is there an easy way to install without cloning, building, and moving the binary?

**Comment by c-nv-s** [comment]
having the same issue

**Comment by ilmari-h** [comment]
Updated package names, it should work now. Install with: `go install github.com/ilmari-h/dlvtui@latest` (Note the changed url!)

And thank you for your interest in the project. I haven't worked on or used it in a while, and not sure if there's been breaking changes with delve. So just a word of warning there.
